AWSTemplateFormatVersion: '2010-09-09'
Description: ''
Parameters:
  Prefix:
    Type: 'String'
    Default: ''
  Suffix:
    Type: 'String'
    Default: ''
  AMIId:
    Type: 'String'
    Default: ''
  KeyPairName:
    Type: 'String'
    Default: ''
  InstanceType:
    Type: 'String'
    Default: ''
  SubnetId:
    Type: 'String'
    Default: ''
Resources:
  EC2InstanceTestFastly01:
    Type: 'AWS::EC2::Instance'
    Properties:
      ImageId: !Ref AMIId
      KeyName: !Ref KeyPairName
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      Tags:
        - Key: 'Name'
          Value: !Sub ${AWS::StackName}